name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/Raj2.com/
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
    env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          SOURCE: "./index.html"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          PORT: 22
          TARGET: ${{ secrets.TARGET_DIR }}
